export const enum EPagePaths {
  HOME = '/',
  BLOG = '/blog',
  CONTACTS = '/contacts',
  ABOUT_US = '/about-us',
  OUR_TEAM = '/our-team',
  FAQ = '/faq',
  SOLUTIONS = '/solutions',
  SERVICES = '/services',
  SOLUTION = '/solutions/:id',
  SERVICE = '/services/:id',
  TEAM_MEMBER = '/our-team/:id',
  SINGLE_BLOG = '/blog/:id',
  ERROR = '*',
}
