export type TTypography =
  | 'EbHeadline1'
  | 'EbHeadline2'
  | 'EbHeadline3'
  | 'BHeadline4'
  | 'BHeadline5'
  | 'BHeadline6'
  | 'SBHeadline7'
  | 'SBHeadline8'
  | 'MHeadline7'
  | 'BParagraph1'
  | 'RParagraph1'
  | 'RParagraph2'
  | 'RParagraph3'
  | 'SBParagraph3'
