name: Test & lint on push
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
jobs:
  lint:
    name: push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: npm
      - name: Install deps
        run: npm ci
      - name: ESLint
        run: npm run lint
      - name: Fix codestyle with prettier
        run: npm run prettier
